version: '2'
services:
  doodlelb:
    scale: 2
    lb_config:
      port_rules:
      - source_port: 8080
        target_port: 8080
        service: doodleshop
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  doodleshop:
    scale: 4
    start_on_create: true
 #   retain_ip: true
    upgrade_strategy:
      start_first: true
    health_check:
      port: 8080
      interval: 5000
      unhealthy_threshold: 5
      request_line: GET /doodles HTTP/1.0
      healthy_threshold: 2
      response_timeout: 5000
